version: "3"

services:

  nginx:
    image: "nginx:1.19-alpine"
    ports:
    - "80"
    volumes:
    - "./docker-compose/nginx/templates:/etc/nginx/templates:ro"
    - ".:/var/www/html:ro"

  php-fpm:
    build:
      context: "./docker-compose/php-fpm"
      args:
        PHP_VERSION: "8.0"
    user: "${UID}:${GID}"
    ports:
    - "9000"
    volumes:
    - ".:/var/www/html"
