version: "3"

services:

  nginx:
    image: "nginx:1.19"
    ports:
    - "80"
    volumes:
    - "./docker/nginx/templates:/etc/nginx/templates"
    - ".:/var/www/html"

  php-fpm:
    build: "./docker/php-fpm"
    user: "${UID}:${GID}"
    ports:
    - "9000"
    volumes:
    - ".:/var/www/html"
