version: "3"

services:

  traefik:
    image: "traefik:2.4"
    container_name: "${COMPOSE_PROJECT_NAME}_traefik"
    ports:
    - "80:80"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
    - "--entrypoints.web.address=:80"
    - "--log.level=DEBUG"
    - "--providers.docker.exposedbydefault=false"
    - "--providers.docker=true"

  nginx:
    image: "nginx:1.19-alpine"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.default.rule=Host(`${PHP_HOSTNAME:-localhost}`)"
    - "traefik.port=80"
    volumes:
    - "./docker-compose/nginx/templates:/etc/nginx/templates:ro"

  php-fpm:
    build:
      context: "./docker-compose/php-fpm"
      args:
        PHP_VERSION: "${PHP_VERSION:-8.0}"
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
    - ".:/var/www/html"
