apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-nginx-templates
data:
  default.conf.template: |
    server {
        listen 80;

        index index.php;
        root /var/www/html/public;
        try_files $uri $uri/ /index.php;

        location ~* \.php$ {
            fastcgi_pass localhost:9000;

            include fastcgi_params;

            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param SCRIPT_NAME     $fastcgi_script_name;
        }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  selector:
    matchLabels:
      name: hello
  template:
    metadata:
      labels:
        name: hello
    spec:
      containers:
      - name: php-fpm
        image: wandersonwhcr/hello
        ports:
        - containerPort: 9000
      - name: nginx
        image: nginx:1.19
        ports:
        - containerPort: 80
        volumeMounts:
        - name: hello-nginx-templates
          mountPath: /etc/nginx/templates
      volumes:
      - name: hello-nginx-templates
        configMap:
          name: hello-nginx-templates
