apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  selector:
    matchLabels:
      name: hello
  template:
    metadata:
      labels:
        name: hello
    spec:
      containers:
      - name: php-fpm
        image: wandersonwhcr/hello
        ports:
        - containerPort: 9000
        livenessProbe:
          exec:
            command: ["php-fpm-healthcheck"]
          initialDelaySeconds: 1
          periodSeconds: 5
      - name: nginx
        image: nginx:1.19
        ports:
        - containerPort: 80
        volumeMounts:
        - name: hello-nginx-templates
          mountPath: /etc/nginx/templates
      volumes:
      - name: hello-nginx-templates
        configMap:
          name: hello-nginx-templates
