name: build

on:
  push:
    branches: ["master"]

jobs:

  checkout:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: find
      run: |
        find .
