name: Build

on:
  push:
    branches: ["main"]

jobs:

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Login
      uses: docker/login-action@v1
      with:
        username: wandersonwhcr
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: wandersonwhcr/hello:latest
